# Generated by Django 2.2 on 2019-09-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otpmodel',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('Contact_no', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('conform_password', models.CharField(max_length=20)),
                ('otps', models.IntegerField(default=0)),
            ],
        ),
    ]
